config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "page#home"
  get 'pages/home' => "page#home"
  get 'pages/about' => "page#about"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :description, presence: true, length: { minimum: 3, maximum: 300 }
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

	def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Created Successfully'
      redirect_to article_path(@article)
    else
      @article.errors.full_messages
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Updated Successfully'
      redirect_to article_path(@article)
    else
      render :edit
    end 
  end

  def destroy
    @article.destroy
    flash[:notice] = "Successfully Deleted."
    redirect_to articles_path
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  #comment to push
  def home

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<!DOCTYPE html>
<html>
<body>
  <% if @article.present? &&  @article.errors.any? %>
    <p> Error messages :- </p>
    <% @article.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  <% end %>
	<%= form_for @article do |f|  %>
       <%= f.label :title %> </br>
       <%= f.text_field :title %></br>
       <%= f.label :description %> </br>
       <%=  f.text_area :description %> </br>
       <%= f.submit %>
	<% end %>
  </br></br>
  <%= link_to :list_articles, articles_path %>
  </br></br>
  <% if @article.id.present? %>
   <%= link_to :show, article_path(@article) %>
  <% end %>
</body>
</html>

app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hey these are all articles</title>
</head>
<body>
  <h1> <%= link_to 'create new article', new_article_path %> </h1>
 <h1>Listing Articles</h1>
 <table>
 	<tr>
 		<th> Title </th>
 		<th> Description </th>
 		<th> Show </th>
 		<th> Edit </th>
 	</tr>
 	<% @articles.each do |article| %>
 		<tr>
 			<td> <%= article.title %></td> 
 			<td> <%= article.description %></td>
 			<td> <%= link_to :show, article_path(article) %></td> 
 			<td> <%= link_to :edit, edit_article_path(article) %></td>
      <td> <%= link_to :delete, article_path(article), method: :delete, data: {confirm: "are you sure?"} %></td> 
 		</tr>
 	<% end %>
 </table>
</body>
</html>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<p>Title: <%= @article.title %> </p>
	<p>Description <%= @article.description %> </p> </br>
	<%= link_to :edit, edit_article_path(@article) %>
  <%= link_to :list_articles, articles_path %>
</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/page/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Hi this is about page</title>
</head>
<body>
	<h1>Welcome to about page</h1>
	<%= link_to 'home', pages_home_path %>
  <%= link_to :new_article, new_article_path %>
</body>
</html>

app/views/page/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Hi this is Home page</title>
</head>
<body>
	<h1>Welcome to Home page</h1>
	<%= link_to :alpha_blog, articles_path %> | <%= link_to 'about', pages_about_path%>
</body>
</html>